name: Schedule Test

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Run a script
        run: echo "This workflow runs on a schedule!"
