name: Schedule Test

on:
  schedule:
    - cron: "40 4 * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
    
      - name: Run a script
        run: echo "This workflow runs on a schedule!"
