
name: Test1
on:
  schedule:
    - cron: '20 4 * * *' # Runs every day at midnight UTC

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run a script
        run: echo "This workflow runs on a schedule!"
